export const lightTheme = {
    themeToggle: 'rgb(75,75,75)',
    background: '#ffffff',
    foreground: '#ffffff',
    foregroundBorder: '#e1e4e8',
    textPrimary: 'rgb(8,8,8)',
    textHighlight: '#37A1D8',
    textHighlightShadow: '#9480FF',
    textSecondary: 'rgb(50,50,50)',
    secondary: '#37A1D8',
    mutedSecondary: '#ffffff',
    button: '#ffffff',
    //buttonBorder: '#e1e4e8',
    buttonHover: 'rgba(157, 201, 255, 0.32)',
    buttonText: '#37A1D8',
    buttonTextHover: '#337ab7',
    skillTag: 'clear',
    textSkillTag: '#5e9516',
    horizontalRuleColor: 'rgb(225,225,225)',
};

export const darkTheme = {
    themeToggle: 'rgb(242,242,242)',
    background: 'rgb(21,19,32)',
    foreground: 'rgb(34,33,45)',
    foregroundBorder: 'rgb(34,33,45)',
    textPrimary: 'rgb(242,242,242)',
    textHighlight: 'rgb(148,128,255)',
    textHighlightShadow: 'rgba(148,128,255,0.1)',
    textSecondary: 'rgb(153,153,153)',
    secondary: 'rgb(148,128,255)',
    mutedSecondary: '#2b2640',
    button: 'rgb(148,128,255)',
    //buttonBorder: 'rgb(148,128,255)',
    buttonHover: '#ff80bf',
    buttonText: 'black',
    buttonTextHover: 'rgb(34,33,45)',
    skillTag: 'rgb(35, 46, 44)',
    textSkillTag: 'rgb(119, 203, 185)',
    horizontalRuleColor: '',
};

export const rainbowTheme1 = {
    themeToggle: 'DeepPink',
    background: 'LightBlue',
    foreground: 'LightSeaGreen',
    foregroundBorder: 'Teal',
    textPrimary: 'Tomato',
    textHighlight: 'Violet',
    textHighlightShadow: 'BlueViolet',
    textSecondary: 'DarkOrchid',
    secondary: 'Violet',
    mutedSecondary: 'DarkMagenta',
    button: 'Violet',
    //buttonBorder: 'rgb(148,128,255)',
    buttonHover: 'DeepPink',
    buttonText: 'DodgerBlue',
    buttonTextHover: 'DeepSkyBlue',
    skillTag: 'Purple',
    textSkillTag: 'Lavender',
    horizontalRuleColor: '',
};

export const rainbowTheme2 = {
    themeToggle: 'Yellow',
    background: 'Aquamrine',
    foreground: 'DeepPink',
    foregroundBorder: 'Fuschia',
    textPrimary: 'DodgerBlue',
    textHighlight: 'ForestGreen',
    textHighlightShadow: 'Green',
    textSecondary: 'GreenYellow',
    secondary: 'HotPink',
    mutedSecondary: 'Indigo',
    button: 'HotPink',
    //buttonBorder: 'rgb(148,128,255)',
    buttonHover: 'LightGreen',
    buttonText: 'LightSkyBlue',
    buttonTextHover: 'LightSeaGreen',
    skillTag: 'LimeGreen',
    textSkillTag: 'Maroon',
    horizontalRuleColor: '',
};
