name: Gatsby Publish

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1     
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        env:
          GATSBY_GOOGLE_TAG: ${{ secrets.GATSBY_GOOGLE_TAG }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --verbose
